# **EXPERIMENT 8**

# **Exploring RNN**

In [20]:
import torch
import torch.nn as nn
import numpy as np

In [21]:
input_size = 9 
hidden_size = 16 
num_layers = 1
actfun = 'tanh'
bias = True



```
input_size = 9
hidden_size = 16
num_layers = 2 # Changing number of layers to 2
actfun = 'relu' # Changing activation function to ReLU
bias = True
```



In [22]:
rnn = nn.RNN(input_size,hidden_size,num_layers,nonlinearity=actfun,bias=bias)
print(rnn)

RNN(9, 16)


In [23]:
seqlength = 5
batchsize = 2

In [24]:
X = torch.rand(seqlength,batchsize,input_size)

In [25]:
hidden = torch.zeros(num_layers,batchsize,hidden_size)

In [26]:
y,h = rnn(X,hidden)
print(f' Input shape: {list(X.shape)}')
print(f'Hidden shape: {list(h.shape)}')
print(f'Output shape: {list(y.shape)}')

 Input shape: [5, 2, 9]
Hidden shape: [1, 2, 16]
Output shape: [5, 2, 16]


In [27]:
y,h1 = rnn(X,hidden)
print(h1), print('\n\n')

tensor([[[0.0000, 0.0000, 0.0713, 0.0798, 0.0316, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0342, 0.1249, 0.0000, 0.1162, 0.2337],
         [0.4574, 0.0000, 0.0000, 0.0000, 0.4199, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0835, 0.0000, 0.0000, 0.0000, 0.6319]]],
       grad_fn=<StackBackward0>)





(None, None)

In [28]:
y,h2 = rnn(X)
print(h2), print('\n\n')

tensor([[[0.0000, 0.0000, 0.0713, 0.0798, 0.0316, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0342, 0.1249, 0.0000, 0.1162, 0.2337],
         [0.4574, 0.0000, 0.0000, 0.0000, 0.4199, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0835, 0.0000, 0.0000, 0.0000, 0.6319]]],
       grad_fn=<StackBackward0>)





(None, None)

In [29]:
print(h1-h2)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],
       grad_fn=<SubBackward0>)


In [30]:
for p in rnn.named_parameters():
  if 'weight' in p[0]:
    print(f'{p[0]} has size {list(p[1].shape)}')

weight_ih_l0 has size [16, 9]
weight_hh_l0 has size [16, 16]


In [31]:
class RNNnet(nn.Module):
  def __init__(self,input_size,num_hidden,num_layers):
    super().__init__()
    self.input_size = input_size
    self.num_hidden = num_hidden
    self.num_layers = num_layers
    self.rnn = nn.RNN(input_size,num_hidden,num_layers)
    self.out = nn.Linear(num_hidden,1)


  def forward(self,x):
    print(f'Input: {list(x.shape)}')
    hidden = torch.zeros(self.num_layers,batchsize,self.num_hidden)
    print(f'Hidden: {list(hidden.shape)}')

    y,hidden = self.rnn(x,hidden)
    print(f'RNN-out: {list(y.shape)}')
    print(f'RNN-hidden: {list(hidden.shape)}')
    o = self.out(y) 
    print(f'Output: {list(o.shape)}')
    return o,hidden

In [32]:
net = RNNnet(input_size,hidden_size,num_layers)
print(net), print(' ')
for p in net.named_parameters():
  print(f'{p[0]} has size {list(p[1].shape)}')
X = torch.rand(seqlength,batchsize,input_size)
y = torch.rand(seqlength,batchsize,1)
yHat,h = net(X)
lossfun = nn.MSELoss()
lossfun(yHat,y)

RNNnet(
  (rnn): RNN(9, 16)
  (out): Linear(in_features=16, out_features=1, bias=True)
)
 
rnn.weight_ih_l0 has size [16, 9]
rnn.weight_hh_l0 has size [16, 16]
rnn.bias_ih_l0 has size [16]
rnn.bias_hh_l0 has size [16]
out.weight has size [1, 16]
out.bias has size [1]
Input: [5, 2, 9]
Hidden: [1, 2, 16]
RNN-out: [5, 2, 16]
RNN-hidden: [1, 2, 16]
Output: [5, 2, 1]


tensor(0.0504, grad_fn=<MseLossBackward0>)